### PR TITLE
Fixes CI (System Tests) in Ruby 2.5

### PR DESCRIPTION
**Pull request by gguuss**

### CODE REVIEW

**Comment by gguuss** [comment]
Looks like texttospeech is failing, I'll look into that.

**Comment by gguuss** [comment]
Looks like CI is down, holding for now.

**Comment by tbpg** [comment]
Heads up, `texttospeech` samples are being removed in #579.

**Comment by gguuss** [comment]
> Heads up, `texttospeech` samples are being removed in #579.

Saves me a step :)

**Comment by gguuss** [comment]
Adding do-not-merge to wait for #579 to land but re-adding to see if this resolves the tests.

**Comment by gguuss** [comment]
Looks like Dialog flow is now failing.

**Comment by gguuss** [comment]
I'm ok with this PR also being the one to remove TTS if #579 is outdated.

**Pull request merged**
