### PR TITLE
feat: eventarc generic snippet – and eventarc pub/sub brushup

### PR DESCRIPTION
**Pull request by grant**
- Adds Eventarc generic sample that replays the received request.
  - Adds unit test.
  - Tested locally.
  - Tested with Cloud Run.
- Brushes up `eventarc/pubsub` README/config.

### CODE REVIEW

**Review by TheRoyalTnetennba — COMMENTED** [review]
some linter issues. otherwise looks great

**Comment by grant** [comment]
Thanks.
Maybe we can add `bundle exec rubocop -a` to a PR template?

**Comment by grant** [comment]
> some linter issues. otherwise looks great

Thanks! I fixed the issues, @TheRoyalTnetennba can you 👍 and merge?

**Review by grayside — APPROVED** [review]
Looks good to me from a product review standpoint. Ruby review required.

A few minor nits:

* Ideally we add a bit more context to the .dockerignore and .gcloudignore. This is inconsistent in Cloud Run samples across languages.
* I can never remember if Gemfile.lock is expected to be committed.

**Comment by grant** [comment]
> * Ideally we add a bit more context to the .dockerignore and .gcloudignore. This is inconsistent in Cloud Run samples across languages.

These ignore files are copied from the Cloud Run Ruby samples: [`.dockerignore`](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/run/helloworld/.dockerignore) and [`.gcloudignore`](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/run/helloworld/.gcloudignore)

> * I can never remember if Gemfile.lock is expected to be committed.

I believe we should commit lockfiles like we do with Cloud Run ([src](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/run/helloworld/Gemfile.lock)).

**Comment by grayside** [comment]
I think the ignore files for the Cloud Run sample should be improved too :) This is a nit/future item.

**Review by TheRoyalTnetennba — APPROVED** [review]

**Comment by grant** [comment]
👋 Please merge when possible. :)

**Pull request merged**
