### PR TITLE
fix(spanner): backup filter with size zero. 

### LINKED ISSUE #755: rspec: Google Cloud Spanner API samples list backups with various filters failed
This test failed!

To configure my behavior, see [the Flaky Bot documentation](https://github.com/googleapis/repo-automation-bots/tree/master/packages/flakybot).

If I'm commenting on this issue too often, add the `flakybot: quiet` label and
I will stop commenting.

---

commit: 9a49927c7f903c79920172b02ab2addb5710c2d3
buildURL: [Build Status](https://source.cloud.google.com/results/invocations/09b3fc4a-2cd2-4ab5-a097-4c0a912e2a4e), [Sponge](http://sponge2/09b3fc4a-2cd2-4ab5-a097-4c0a912e2a4e)
status: failed
<details><summary>Test output</summary><br><pre>Failure/Error:
  expect(captured_output).to include(
    "All backups with a size greater than 500 bytes:\n#{backup.backup_id}"
  )

  expected "All backups\ntest_bu_9fa1534a1a6c8e6d\ntest_bu_b732966023037733\nAll backups with backup name contai...fa1534a1a6c8e6d\nAll backups with pagination:\ntest_bu_9fa1534a1a6c8e6d\ntest_bu_b732966023037733\n" to include "All backups with a size greater than 500 bytes:\ntest_bu_9fa1534a1a6c8e6d"
  Diff:
  @@ -1,17 +1,33 @@
  -All backups with a size greater than 500 bytes:\ntest_bu_9fa1534a1a6c8e6d
  +All backups
  +test_bu_9fa1534a1a6c8e6d
  +test_bu_b732966023037733
  +All backups with backup name containing "test_bu_9fa1534a1a6c8e6d":
  +test_bu_9fa1534a1a6c8e6d
  +All backups for databases with a name containing "test_db_9fa1534a1a6c8e6d":
  +test_bu_9fa1534a1a6c8e6d
  +All backups that expire before a timestamp:
  +test_bu_9fa1534a1a6c8e6d
  +test_bu_b732966023037733
  +All backups with a size greater than 500 bytes:
  +test_bu_b732966023037733
  +All backups that were created after a timestamp that are also ready:
  +test_bu_9fa1534a1a6c8e6d
  +All backups with pagination:
  +test_bu_9fa1534a1a6c8e6d
  +test_bu_b732966023037733
./spec/spanner_samples_spec.rb:1616:in `block (2 levels) in <top (required)>'</pre></details>

### PR DESCRIPTION
**Pull request by jiren**
Fixes #755 

- [x] **Tests** pass
- [x] **Lint** pass: `bundle exec rubocop`
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Review by skuruppu — COMMENTED** [review]
So this fix will be reverting the change that @thiagotnunes made. I'm not sure if that's the right approach.

**Review by thiagotnunes — CHANGES_REQUESTED** [review]
We need to use the `database.earliest_version_time` here, instead of `Time.now` due to possible clock skew issues

**Comment by jiren** [comment]
> We need to use the `database.earliest_version_time` here, instead of `Time.now` due to possible clock skew issues

@skuruppu and @thiagotnunes 

I am facing an issue regarding database version size. It is always `0` after data insert with `version_time = database.earliest_version_time`.
I think it is due to tests taking backup right after data insert. In a small period of time `database.earliest_version_time` is always create the time of the database.

So in tests instead of filtering `filter: "size_bytes > 500"` can use `backups size >=0`?

**Comment by thiagotnunes** [comment]
It should be `> 0`, since we want to verify that the backup has data. Let me investigate this a bit, I will get back to you.

**Comment by thiagotnunes** [comment]
@jiren I evaluated the issue and since we are creating a backup from 1 hour ago (that is the default version retention period, reflected in the earliest version time), the tests will not succeed. 

You are correct, let's just change the `backups size >= 0` for now, thanks!

**Review by thiagotnunes — APPROVED** [review]

**Pull request merged**
