### PR TITLE
Updates Cloud-KMS sample code to use V1 libraries.

### PR DESCRIPTION
**Pull request by philcoakley**

### CODE REVIEW

**Comment by frankyn** [comment]
Hi @philcoakley!

Thanks for sending a PR to update the KMS samples. Tests are not done by Circle automatically for PRs not in a branch of `GoogleCloudPlatform:master`. I'll test the changes after this comment. 

Besides the require statement at the beginning of each sample. How did the API change after updating the version from v1_beta to v1?

Thanks again!

**Comment by philcoakley** [comment]
Hi Frank,

No changes other than the version#!  Just trying to get rid of 'v1beta1'
now that the service is GA.

Cheers
Phil

On Mar 16, 2017 6:21 PM, "Frank Natividad" <notifications@github.com> wrote:

Hi @philcoakley <https://github.com/philcoakley>!

Thanks for sending a PR to update the KMS samples. Tests are not done by
Circle automatically for PRs not in a branch of GoogleCloudPlatform:master.
I'll test the changes after this comment.

Besides the require statement at the beginning of each sample. How did the
API change after updating the version from v1_beta to v1?

Thanks again!

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/148#issuecomment-287208833>,
or mute the thread

**Comment by frankyn** [comment]
@philcoakley,

Great, thanks for answering my question. I have one request before I can approve your PR. Please update the Gemfile.lock. It's currently set to use version 0.9.26 of google-api-client. 

`bundle update`

Tests passed fine once the Gemfile.lock was updated locally.

**Comment by philcoakley** [comment]
@frankyn Committed gemfile update.  Are you able to re-run tests? (Or alternatively, point me to instructions?)

**Comment by frankyn** [comment]
Thanks @philcoakley!

I tested the updates, and they work. I didn't add instructions for testing locally, sorry about that. You can test the samples by first following the setup instructions in the `README.md` and then using:

```
bundle exec rspec
```

One last thing, in the `Gemfile` can you update:
```
gem "google-api-client", "~> 0.9"
```
to
```
gem 'google-api-client', '~> 0.10'
```

**Comment by philcoakley** [comment]
@frannkyn All set.  I tried running the tests but I'm getting some invalid argument errors, so I think there may be some setup step I missed.

**Comment by frankyn** [comment]
@philcoakley, for clarity could you add your error logs. I'll merge now.

**Comment by philcoakley** [comment]
$ export GOOGLE_CLOUD_PROJECT=pcoakley-test-project
$ bundle exec rspec
............FF.

Failures:

  1) Key Management Service can add a member to a key ring policy
     Failure/Error:
       $add_member_to_keyring_policy.call(
         project_id: @project_id,
         key_ring_id: @key_ring_id,
         member: "serviceAccount:test-account@#{@project_id}.iam.gserviceaccount.com",
         role: "roles/owner",
         location: @location
       )

     Google::Apis::ClientError:
       badRequest: Request contains an invalid argument.
     # ./kms.rb:385:in `block in <top (required)>'
     # ./spec/kms_spec.rb:720:in `block (3 levels) in <top (required)>'
     # ./spec/kms_spec.rb:719:in `block (2 levels) in <top (required)>'

  2) Key Management Service can get a key ring policy
     Failure/Error: kms_client.set_key_ring_iam_policy resource, policy_request

     Google::Apis::ClientError:
       badRequest: Request contains an invalid argument.
     # ./spec/kms_spec.rb:214:in `add_test_member_to_keyring_policy'
     # ./spec/kms_spec.rb:741:in `block (2 levels) in <top (required)>'

Finished in 24.91 seconds (files took 0.41254 seconds to load)
15 examples, 2 failures

Failed examples:

rspec ./spec/kms_spec.rb:698 # Key Management Service can add a member to a key ring policy
rspec ./spec/kms_spec.rb:740 # Key Management Service can get a key ring policy

**Comment by frankyn** [comment]
@philcoakley, we have use a test serviceAccount for key ring policy tests. I'll make a note to call that out somewhere, not sure where.

The tests passed in master. Thanks!

**Pull request merged**
