### PR TITLE
texttospeech: delete from ruby-docs-samples

### PR DESCRIPTION
**Pull request by viacheslav-rostovtsev**
samples moved to https://github.com/googleapis/google-cloud-ruby/tree/master/google-cloud-text_to_speech/samples
documentation updated

### CODE REVIEW

**Comment by gguuss** [comment]
@viacheslav-rostovtsev you will need to resolve the conflicts to merge.

**Comment by viacheslav-rostovtsev** [comment]
@gguuss done. I don't have permissions to merge either this or https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/580

**Comment by gguuss** [comment]
I'm in favor of force committing this, the fix for the presubmit failure is in my PR.

**Comment by gguuss** [comment]
@tbpg do you have admin permissions on this repo? I'd like to merge this to unblock #578

**Comment by busunkim96** [comment]
Hiya, when you move samples that are actively being used in cloud.google.com documentation, please update the snippets includes internally. Otherwise the "view on GitHub" button breaks.

**Comment by gguuss** [comment]
Mea culpa - I had assumed this was removed from the docs or migrated.

**Pull request merged**
