### PR TITLE
Speech: fix undefined method 'project_id'

### PR DESCRIPTION
**Pull request by vietkungfu**

### CODE REVIEW

**Comment by frankyn** [comment]
@vietkungfu could you sign the Contributor License Agreement and then comment "I signed it!"? That's the only way we can proceed with your PR. 

Thank you!

**Comment by remi** [comment]
Fixed by #158

**Comment by vietkungfu** [comment]
Sorry for my late reply !
I signed it!

**Comment by remi** [comment]
Thanks for following-up and for fixing this!

**Pull request merged**
