### PR TITLE
Adds list states

### PR DESCRIPTION
**Pull request by gguuss**
Missed one method in initial commit!

### CODE REVIEW

**Comment by gguuss** [comment]
@frankyn - I missed an API call for listing device states. Added in this commit.

**Comment by remi** [comment]
This commit only has iot.rb, it's missing the test

**Comment by frankyn** [comment]
Hey @gguuss! Apologies for the delay. +1 to @remi's comment. Could you add a test for this API call?

**Comment by gguuss** [comment]
Added new test for list states and included list configs as well (also missing)

**Comment by gguuss** [comment]
@frankyn iot_test.rb added, I globbed in the list configs and list state into a single test because the build-up on these stupid tests is long and takes forever

**Comment by frankyn** [comment]
Thanks @gguuss, the PR LGTM, could you please update the spec to hide the verbose messaging: Here's an [example](https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/kms/spec/kms_spec.rb#L291-L294). 

I also see output coming from tests, please update the specs so they don't print out from your tests. 
```
Device: patches_unauth_device
	Blocked: 
	Last Event Time: 
	Last State Time: 
	Name: projects/cloud-samples-tests-ruby/locations/us-central1/registries/A872a15e7e11c56cbcreate_delete_test_patches/devices/2657738874939473
```

Apologies for the delay in review. Thanks!

**Comment by frankyn** [comment]
Waiting for tests to complete to review. Thanks @gguuss!

**Pull request merged**
