### PR TITLE
[Kokoro] Add Auth Tests

### PR DESCRIPTION
**Pull request by frankyn**
This is a PR to use all system tests during a Kokoro build.

### CODE REVIEW

**Comment by frankyn** [comment]
@SurferJeffAtGoogle PTAL when you have a moment.

**Comment by broady** [comment]
Could you run shellcheck on this? (Should be installed on your Google workstation, but otherwise, I think this is it: https://github.com/koalaman/shellcheck)

I think we should have `set -e -u -o pipefail`, for example. (but I don't think shellcheck would pick that up)

**Comment by frankyn** [comment]
@broady, I thought to not fail the script on the first failure. Do you recommend this over displaying failures instead with an overall status test?

**Comment by broady** [comment]
If we expect things to fail, trap the status with something like:

```
exit_status=0
function set_failed_status {
  exit_status=1
}

./run_test || set_failed_status

exit $exit_status
```

**Comment by frankyn** [comment]
@broady PTAL at the script now. Thanks!

**Pull request merged**
