### PR TITLE
fix: translate replaced wrong method

### PR DESCRIPTION
**Pull request by munkhuushmgl**

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
Thanks! The tests for this sample are failing. Could you update

**Comment by munkhuushmgl** [comment]
@TheRoyalTnetennba I am having hard time setting up ruby env.

**Comment by dazuma** [comment]
It can be very difficult to set up the test environment (because you need a test project and the right credentials, etc.). @munkhuushmgl can you at least comment on what changes we should make in the test expectations (see https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/master/translate/spec/translate_v3_samples_spec.rb#L80-L100)? Then @TheRoyalTnetennba or I can make the actual test adjustment.

Currently, the test is failing in this way with your change:
```
  expect do
    translate_v3_translate_text_with_glossary
  end.to output("Translated text: Bonjour le monde!\n").to_stdout

  expected block to output "Translated text: Bonjour le monde!\n" to stdout, but output "Translated text: \n"
```

**Comment by munkhuushmgl** [comment]
@dazuma @TheRoyalTnetennba Sorry for late response,

Looks like glossary source and target language hard-coded https://github.com/GoogleCloudPlatform/ruby-docs-samples/blob/619cc8d22dd4ba89680d221651d52f8e96574870/translate/translate_v3_create_glossary.rb#L32

So I think we have to assert the following  Japanese output according to python translate samples (please refer to python samples)

https://github.com/GoogleCloudPlatform/python-docs-samples/blob/9a9ce78e9d3ea07f1aa713d06e1a5910d8666516/translate/cloud-client/translate_v3_translate_text_with_glossary_test.py#L62

**Comment by dazuma** [comment]
Thanks, so the translation samples have been moved to https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-translate/samples and we made sure this correction was made during that process.

**Pull request closed without merging**
