### PR TITLE
docs: Update Security Command Center UpdateNotificationConfig sample, adding filter to mutable field

### PR DESCRIPTION
**Pull request by hannah-tsai**
Fixes b/155346619
Add "filter" to mutable fields for UpdateNotificationConfig.

### CODE REVIEW

**Comment by hannah-tsai** [comment]
Hi 

How can I have write access to securitycenter directory?

**Comment by hannah-tsai** [comment]
Hi 
Is this repo still being maintained?

**Comment by TheRoyalTnetennba** [comment]
Could you resolve merge conflicts? Does running `bundle exec rubocop` from the repo-root directory turn up anything?

**Comment by hannah-tsai** [comment]
> Could you resolve merge conflicts? Does running `bundle exec rubocop` from the repo-root directory turn up anything?

'497 files inspected, no offenses detected' after running `bundle exec rubocop`, from the error msg, looks like it requires write access to resolve the conflict. I'm sure if it's possible to grant me access to that?

**Comment by hannah-tsai** [comment]
Canceling this PR and move change list to https://github.com/googleapis/google-cloud-ruby/pull/7102

**Pull request closed without merging**
