### PR TITLE
Swap ports for Endpoints docker image.

### PR DESCRIPTION
**Pull request by jeffmendoza**
Need to swap ports to line up with samples in other languages.

### CODE REVIEW

**Comment by jeffmendoza** [comment]
note, updated `gcr.io/google-samples/echo-ruby:1.0` is pushed that listens on 8080.

**Comment by remi** [comment]
Makes sense!  LGTM 👍 

For additional context, where is `Dockerfile.custom` used?  Can I find it referenced by one of the [Endpoints Quickstarts](https://cloud.google.com/endpoints/docs/quickstarts)?

**Comment by jeffmendoza** [comment]
Not used explicitly. The image will be a part of the GKE quickstarts, and I wan to have the source of the Docker image in the repo.

**Comment by remi** [comment]
Oh, gotcha!!  Sgtm 😄

**Pull request merged**
