### PR TITLE
Translate API no longer requires an API key.

### PR DESCRIPTION
**Pull request by jmdobry**
See 

- GoogleCloudPlatform/php-docs-samples#248
- GoogleCloudPlatform/python-docs-samples#659

### CODE REVIEW

**Comment by jmdobry** [comment]
I don't know why the tests are failing. Help?

**Comment by puneith** [comment]
Lots of stuff removed from Gemfile.lock? And I see some of the test errors like faraday missing due to that?

**Comment by jmdobry** [comment]
I have no idea what I'm doing. 🐶

**Comment by frankyn** [comment]
I attempted to reproduce and I was able to get passed it by including "google-cloud" gem in the Gemfile. Many gems are not installed when only using "google-cloud-translate". I'm not sure why.

**Comment by frankyn** [comment]
It was a bug, and it has been fixed. I just committed an updated Gemfile.lock.

**Comment by puneith** [comment]
@frankyn Build still red.

**Comment by frankyn** [comment]
@puneith, the red is for flaky tests. Translate tests passed :)

**Comment by jmdobry** [comment]
Thanks!

**Pull request merged**
