### PR TITLE
Add bigquery sample

### PR DESCRIPTION
**Pull request by bshaffer**
This PR depends on #5. 

See f7f143b for the changes proposed specifically by this PR.

### CODE REVIEW

**Comment by bshaffer** [comment]
I also need to add this to the `.travis.yml` matrix once that gets updated.

**Comment by bshaffer** [comment]
these tests are failing because this is a PR from a different branch :(

**Comment by jeffmendoza** [comment]
yeah make a branch in the gcp repo "<your name>/add-bigquery" and open the PR from that one

**Comment by bshaffer** [comment]
@jeffmendoza I really don't like that solution long term... I'd rather us just skip the tests in travis and run them locally before we submit/merge

**Comment by bshaffer** [comment]
closing in favor of #7

**Pull request closed without merging**
