### PR TITLE
add vision example

### PR DESCRIPTION
**Pull request by gwmoura**
this PR adds a ruby example for Vision API using the `gcloud` gem

### CODE REVIEW

**Comment by gwmoura** [comment]
@remi all builds failed when runned the command "openssl aes-256-cbc -K $encrypted_aeb4e2af7332_key -iv $encrypted_aeb4e2af7332_iv -in client_secrets.json.enc -out client_secrets.json -d"`

how can I rebuild?

**Comment by remi** [comment]
@gwmoura Sorry!  Travis always fails for external pull requests because the service account key we use for testing cannot be decrypted for security reasons.

This contribution is *great*!  Thank you so much, especially for using the latest, renamed [`google-cloud` RubyGem](googlecloudplatform.github.io/google-cloud-ruby/)

I already have a [branch that includes Cloud Vision samples](https://github.com/gwmoura/ruby-docs-samples/tree/vision-sample/vision) for label, face, and landmark detection that I'm working on for our [Google Cloud Vision tutorials](https://cloud.google.com/vision/docs/tutorials) but I'll rework my samples so they're based on your commits to get your contribution in, probably by next week.  I'll keep this PR open until then.

*Thanks so much!*   Let me know if you have any feedback 😄

**Comment by gwmoura** [comment]
@remi I'm so sorry! I didn't saw your branch. But ok, no problem, You can do as you think better, If no has problem I'm gonna help you, sending PRs for you. ok?

**Comment by remi** [comment]
Sending pull requests is *great!!*

I'll run your specs locally for any contributions you want to submit in the future (*and I'll fix that Travis error you got on this PR* 😄 )

Closing this in favor of #50 which incorporates some of your work into samples for label, landmark, and face detection with snippets for the existing [Cloud Vision tutorials](https://cloud.google.com/vision/docs/tutorials)

Thanks again!

**Comment by gwmoura** [comment]
Thanks @remi :wink:

**Pull request closed without merging**
