### PR TITLE
Add or update Cloud KMS samples

### PR DESCRIPTION
**Pull request by sethvargo**
This adds or updates the Cloud KMS samples to fill in the missing gaps.

### CODE REVIEW

**Comment by frankyn** [comment]
Passing over to @GoogleCloudPlatform/yoshi-ruby. Apologies bandwidth is limited this week.

**Comment by sethvargo** [comment]
Test failure seems to be a rate limit for GCS?

**Comment by frankyn** [comment]
+1, the retry settings are failing. Rerunning.

**Comment by frankyn** [comment]
@TheRoyalTnetennba were tests updated to run all sample tests for each PR? Might be recent but wanted to double check.

**Comment by sethvargo** [comment]
Kokoro seems happy now

**Comment by dazuma** [comment]
@sethvargo The samples generally look good to me. When we make this change, we're going to have to update links from the cloud.google.com pages, otherwise the existing links will break because the old files are being deleted in this PR. I might suggest splitting it into two PRs, one to add the new samples and one to delete the old files, so that users don't see broken sample links between the time this PR gets merged and the corresponding cloud.google.com updates get published.

**Comment by sethvargo** [comment]
@dazuma post-review, I'll have a CL staged with TW approval to merge immediately after this PR is merged. That's how we've done it with the other languages with no interruption.

**Comment by dazuma** [comment]
@sethvargo Okay, SGTM.

**Pull request merged**
