### PR TITLE
adds e2e tests to run-all.sh

### PR DESCRIPTION
**Pull request by bshaffer**
`E2E=true` is required for the e2e tests to run

### CODE REVIEW

**Comment by frankyn** [comment]
Thanks Brent! It's looking great :) 

I did a brief review of Circle CI and found [CircleCI-Run-357]( https://circleci.com/gh/GoogleCloudPlatform/ruby-docs-samples/357) didn't propagate an error in Datastore using Ruby 2.2.5. 

After digging around a little bit I found this: [Stackoverflow Solution](http://stackoverflow.com/questions/4667509/problem-accessing-a-global-variable-from-within-a-while-loop). The issue exists from the piped path list into the while loop found in **run-all.sh**. A workaround would either be to save the list of directories in a variable without piping or use **process substitution**. I don't think process substitution is very readable though.

**Comment by bshaffer** [comment]
Good catch, I've added `set -ex` to the bash script so it fails immediately

**Comment by bshaffer** [comment]
Tests now fail as expected :D

**Comment by bshaffer** [comment]
Tests pass for real this time, PTAL!

**Comment by frankyn** [comment]
@bshaffer, Thanks! I reviewed it and it LGTM. 

I have a question, is the following still true? I'm not sure what this is referring to in your PR. 

> Good catch, I've added set -ex to the bash script so it fails immediately

**Comment by bshaffer** [comment]
@frankyn no, a later comment removed it 👍

**Pull request merged**
