### PR TITLE
Update standard samples to use ruby 3.0 

### PR DESCRIPTION
**Pull request by wietsevenema**
## Description

Ruby 3.0 is now generally available on App Engine standard, this PR updates standard samples.

- appengine/standard-analytics
- appengine/standard-cloud-tasks
- appengine/standard-datastore
- appengine/standard-hello_configs
- appengine/standard-hello_world
- appengine/standard-metadata-server
- appengine/standard-storage

## Checklist
- [x] **Tests** pass
- [x] **Lint** pass: `bundle exec rubocop`
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by bajajneha27** [comment]
Hi @wietsevenema 
Thanks for opening this pull request. The CI for Ruby oldest is failing, would you be able to take a look at it and fix it?

**Comment by wietsevenema** [comment]
The CI is failing because it tests on Ruby 2.5.9, which is EOL - support ended 1 year and 8 months ago. I suggest to update the CI to test on a supported Ruby version.

**Comment by bajajneha27** [comment]
The CI failure of `Ruby Oldest` seems to be happening on latest [PR](https://fusion.corp.google.com/runanalysis/buildlogs/prod:cloud-devrel%2Fruby%2Fruby-docs-samples%2Fpresubmit%2Fruby-oldest/prod:cloud-devrel%2Fruby%2Fruby-docs-samples%2Fpresubmit%2Fruby-oldest/KOKORO/75dbb098-8835-403d-9b80-fb36077349d2/1670524014215/build%20%232181/Targets) too and not related to this particular PR.

**Review by bajajneha27 — APPROVED** [review]

**Comment by bajajneha27** [comment]
Can be merged once [PR#1035](https://github.com/GoogleCloudPlatform/ruby-docs-samples/pull/1035) is merged.

**Pull request merged**
