### PR TITLE
Add a Hello World sample for Ruby GAE Standard

### PR DESCRIPTION
**Pull request by dazuma**
Proposing to keep App Engine standard environment samples in a new directory, separate from the flexible environment samples. The samples will be very similar, but there will be distinctions, and I think they do need to be kept separate.

This adds the directory and a README, and adds the quickstart sample.

### CODE REVIEW

**Comment by TheRoyalTnetennba** [comment]
LGTM pending bundler version fix

**Comment by dazuma** [comment]
Oh geez... bundler 2... I'll downgrade the Gemfile.lock.

**Comment by TheRoyalTnetennba** [comment]
@tbpg kokoro-cloud-samples-ruby-0@cloud-samples-ruby-test-0.iam.gserviceaccount.com does not have serviceusage.services.use access to project 623682833436

**Comment by tbpg** [comment]
Sorry about that. Fixing in #428.

**Comment by dazuma** [comment]
@TheRoyalTnetennba Can I get you to merge this? I don't have permissions. Actually, do you know who owns this repo? I should get on the list.

**Comment by dazuma** [comment]
Actually, hold off on the merge here. I just found an issue.

**Comment by dazuma** [comment]
Okay, just needed to fix a tag. This is ready for merge.

**Pull request merged**
