### PR TITLE
all: update Gemfile.lock files for security updates

### PR DESCRIPTION
**Pull request by tbpg**
I'll cancel Kokoro tests since they aren't configured for the `appengine` directory.

### CODE REVIEW

**Comment by frankyn** [comment]
@tbpg the title is to enable storage tests, but the files only have Gemfile.lock's to update. Is the title incorrect and this is more about updating Gemfile.lock's?

**Comment by tbpg** [comment]
Fixed - mixed up between branches.

**Comment by frankyn** [comment]
Thanks Pending CircleCI then.

**Comment by tbpg** [comment]
Circle is now green (had to update one test due to a Capybara change).

**Pull request merged**
