### PR TITLE
fix: run/rails/cloudbuild.yaml step 2 args typo

### PR DESCRIPTION
**Pull request by hy01n**
## Checklist
- [ ] **Tests** pass
- [ ] **Lint** pass: `bundle exec rubocop`
- [x] Please **merge** this PR for me once it is approved.

### CODE REVIEW

**Comment by dazuma** [comment]
@hy01n Agreed this should be done for consistency, but I don't think it's actually strictly necessary. Are you having problems with the tutorial that are solved by this change?

**Comment by hy01n** [comment]
@dazuma Nope. I had an error in my build process, but later I came to know that this typo was trivial. Anyway it will be better to fix this typo to prevent any confusion with beginners.

**Comment by dazuma** [comment]
@hy01n Agreed, it would be good to fix it anyway. I'm happy to merge this, if you can sign the CLA.

**Comment by hy01n** [comment]
@googlebot I signed it!

**Review by dazuma — APPROVED** [review]

**Comment by dazuma** [comment]
Thanks much @hy01n ! Merging.

**Pull request merged**
